"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n$1h66+fm&00mka9a0-wo-&lr9jxs55i&kz9lnjj0%u55a8*_g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost", "70.34.245.3", "sonderhomefeeling.com", "www.sonderhomefeeling.com"]


# Application definition

INSTALLED_APPS = [
    'core.admin_site.SonderAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_countries',
    'shop',
    "imageops",
    "easy_thumbnails",
    "image_cropping",
    "ckeditor",
    "ckeditor_uploader",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "frontend" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'sonder_db'),
        'USER': os.getenv('POSTGRES_USER', 'sonder_user'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'db'),                   # имя сервиса из compose
        'PORT': os.getenv('DB_PORT', '5432'),
        'CONN_MAX_AGE': 60,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "frontend" / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CHECKOUT_ALLOWED_COUNTRIES = ["BY", "RU"]

IMAGEOPS_MAX_DIMS = (1800, 1800)      # по длинной стороне
IMAGEOPS_QUALITY = 90                 # 1–95
IMAGEOPS_FORCE_WEBP = False       # True => всё конвертить в WebP
IMAGEOPS_STRIP_EXIF = True            # вырезать метаданные
IMAGEOPS_ONLY_ON_CHANGE = True        # сжимать только когда файл заменили
IMAGEOPS_ENABLE = True                # глобальный выключатель


from easy_thumbnails.conf import Settings as thumbnail_settings
THUMBNAIL_PROCESSORS = (
    'image_cropping.thumbnail_processors.crop_corners',
) + thumbnail_settings.THUMBNAIL_PROCESSORS

IMAGE_CROPPING_THUMB_SIZE = (960, 410)

YANDEX_MAPS_API_KEY = os.environ.get("YANDEX_MAPS_API_KEY", "")

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    "default": {
        "height": 400,
        # ВАЖНО: разрешаем стили/классы, чтобы не вырезались
        "extraAllowedContent": "*(*);*{*}",   # или "allowedContent": True
        "removePlugins": "stylesheetparser",
        "extraPlugins": ",".join([
            "font",          # семейство и размер шрифта
            "colorbutton",   # цвет текста/фона
            "justify",       # выравнивание
        ]),
        "toolbar": [
            {"name": "basicstyles", "items": [
                "Bold","Italic","Underline","Strike","-","RemoveFormat"
            ]},
            {"name": "paragraph", "items": [
                "NumberedList","BulletedList","-","Outdent","Indent","-",
                "JustifyLeft","JustifyCenter","JustifyRight","JustifyBlock"
            ]},
            {"name": "styles", "items": [
                "Format","Font","FontSize","TextColor","BGColor"
            ]},
            {"name": "links", "items": ["Link","Unlink"]},
            {"name": "insert", "items": ["Image","Table","HorizontalRule"]},
            {"name": "document", "items": ["Source"]},  # можно убрать
        ],
        # Добавляем кастомные шрифты (названия до слэша — как в выпадашке)
        "font_names": (
            "Cygre Bookit/Cygre Bookit;"
            "Cygre Book/Cygre Book;"
            "Cygre/Cygre;"
            "Arial/Arial, Helvetica, sans-serif;"
            "Georgia/Georgia, serif;"
            "Times New Roman/Times New Roman, Times, serif;"
            "Monospace/Monaco, Courier New, monospace;"
        ),
        # Список размеров. Можно задать любые px/pt/em/rem
        "fontSize_sizes": "12/12px;14/14px;16/16px;18/18px;20/20px;22/22px;24/24px;28/28px;32/32px;36/36px;48/48px;64/64px;",
        # Чтобы классы/стили в админке выглядели ближе к фронту:
        "contentsCss": [
            # CKEditor base
            "//cdn.ckeditor.com/4.22.1/full-all/contents.css",
            # твои шрифты/базовые стили (пути проверь)
            "/static/css/normalize.css",
            "/static/css/sonderhomefeeling.webflow.css",
            "/static/css/app.css",
        ],
        "format_tags": "p;h2;h3;h4;pre",  # можно оставить, но теперь есть и Font/FontSize
    }
}


CSRF_TRUSTED_ORIGINS = [
    "https://sonderhomefeeling.com",
    "https://www.sonderhomefeeling.com",
]
