# Generated by Django 5.2.5 on 2025-09-02 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productphoto',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Фото товара', 'verbose_name_plural': 'Фото товара'},
        ),
        migrations.RenameField(
            model_name='productphoto',
            old_name='order',
            new_name='position',
        ),
        migrations.AddField(
            model_name='productphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productphoto',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt-текст'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='image',
            field=models.ImageField(upload_to='products/photos/', verbose_name='Фото'),
        ),
    ]
