# Generated by Django 5.2.5 on 2025-09-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productphoto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст «Дополнительно»'),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_title',
            field=models.CharField(default='Дополнительно', max_length=50, verbose_name='Заголовок блока «Дополнительно»'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_title',
            field=models.CharField(default='Размер', max_length=50, verbose_name='Заголовок блока размера'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_value',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Размер / объём'),
        ),
    ]
