# Generated by Django 5.2.5 on 2025-09-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_extra_text_product_extra_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Баннер (реком. 1920×820)'),
        ),
        migrations.AddField(
            model_name='category',
            name='banner_pos',
            field=models.CharField(choices=[('center', 'По центру'), ('top', 'Сверху'), ('bottom', 'Снизу'), ('left', 'Слева'), ('right', 'Справа')], default='center', max_length=10, verbose_name='Фокус кадра'),
        ),
        migrations.AddField(
            model_name='category',
            name='banner_text',
            field=models.TextField(blank=True, verbose_name='Текст на баннере'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_desc',
            field=models.TextField(blank=True, max_length=240, verbose_name='Короткое описание'),
        ),
    ]
