# Generated by Django 5.2.5 on 2025-09-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_banner_image_category_banner_pos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTabSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Баннер (реком. 1920×820)')),
                ('banner_pos', models.CharField(choices=[('center', 'По центру'), ('top', 'Сверху'), ('bottom', 'Снизу'), ('left', 'Слева'), ('right', 'Справа')], default='center', max_length=10, verbose_name='Фокус кадра')),
                ('banner_text', models.TextField(blank=True, verbose_name='Текст на баннере')),
            ],
            options={
                'verbose_name': 'Вкладка «Новинки»',
                'verbose_name_plural': 'Вкладка «Новинки»',
            },
        ),
    ]
