# Generated by Django 5.2.5 on 2025-09-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_newtabsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Новинка'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='shop_produc_created_ed077b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='shop_produc_is_acti_2257ae_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_new'], name='shop_produc_is_acti_d25c76_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='shop_produc_categor_6c2d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='productphoto',
            index=models.Index(fields=['product', 'is_active', 'position'], name='shop_produc_product_53ac8d_idx'),
        ),
    ]
