# Generated by Django 5.2.7 on 2025-10-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_is_active_alter_product_is_new_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Фоновое фото (герой)')),
                ('hero_pos', models.CharField(choices=[('center', 'По центру'), ('top', 'Сверху'), ('bottom', 'Снизу'), ('left', 'Слева'), ('right', 'Справа')], default='center', max_length=10, verbose_name='Фокус кадра')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
    ]
