# Generated by Django 5.2.7 on 2025-10-07 16:22

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_homepagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_crop',
            field=image_cropping.fields.ImageRatioField('hero_image', '1920x820', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка героя'),
        ),
    ]
