# Generated by Django 5.2.7 on 2025-10-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_homepagesettings_hero_crop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesettings',
            name='hero_pos',
        ),
    ]
