# Generated by Django 5.2.7 on 2025-10-07 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_homepagesettings_hero_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='featured_1',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.category', verbose_name='Блок 1 — раздел'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='featured_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/featured/', verbose_name='Блок 1 — фон'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='featured_1_title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Блок 1 — подпись'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='featured_2',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.category', verbose_name='Блок 2 — раздел'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='featured_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/featured/', verbose_name='Блок 2 — фон'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='featured_2_title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Блок 2 — подпись'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='featured_3',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.category', verbose_name='Блок 3 — раздел'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='featured_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/featured/', verbose_name='Блок 3 — фон'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='featured_3_title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Блок 3 — подпись'),
        ),
    ]
