# Generated by Django 5.2.7 on 2025-10-07 19:41

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_homepagesettings_featured_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='featured_1_crop',
            field=image_cropping.fields.ImageRatioField('featured_1_image', '1000x1000', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка блока 1'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='featured_2_crop',
            field=image_cropping.fields.ImageRatioField('featured_2_image', '1000x1000', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка блока 2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='featured_3_crop',
            field=image_cropping.fields.ImageRatioField('featured_3_image', '1000x1000', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка блока 3'),
        ),
    ]
