# Generated by Django 5.2.7 on 2025-10-08 09:20

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_homepagesettings_featured_1_crop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_crop',
            field=image_cropping.fields.ImageRatioField('banner_image', '1920x820', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка баннера'),
        ),
        migrations.AddField(
            model_name='newtabsettings',
            name='banner_crop',
            field=image_cropping.fields.ImageRatioField('banner_image', '1920x820', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка баннера'),
        ),
    ]
