# Generated by Django 5.2.7 on 2025-10-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_category_banner_crop_newtabsettings_banner_crop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='banner_pos',
        ),
        migrations.RemoveField(
            model_name='newtabsettings',
            name='banner_pos',
        ),
    ]
