# Generated by Django 5.2.7 on 2025-10-08 09:33

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_category_banner_pos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='О НАС', max_length=120, verbose_name='Заголовок')),
                ('intro_text', models.TextField(blank=True, default='', verbose_name='Интро-текст')),
                ('block1_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Блок 1 — фото')),
                ('block1_crop', image_cropping.fields.ImageRatioField('block1_image', '1000x1000', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка блока 1')),
                ('block1_text', models.TextField(blank=True, default='', verbose_name='Блок 1 — текст')),
                ('block2_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Блок 2 — фото')),
                ('block2_crop', image_cropping.fields.ImageRatioField('block2_image', '1000x1000', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка блока 2')),
                ('block2_text', models.TextField(blank=True, default='', verbose_name='Блок 2 — текст')),
                ('block3_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Блок 3 — фото')),
                ('block3_crop', image_cropping.fields.ImageRatioField('block3_image', '1000x1000', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка блока 3')),
                ('block3_text', models.TextField(blank=True, default='', verbose_name='Блок 3 — текст')),
            ],
            options={
                'verbose_name': 'Страница «О нас»',
                'verbose_name_plural': 'Страница «О нас»',
            },
        ),
    ]
