# Generated by Django 5.2.7 on 2025-10-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_aboutpagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='КОНТАКТЫ', max_length=120, verbose_name='Заголовок')),
                ('address_text', models.TextField(blank=True, default='Адрес мастерской:\nул. Тимирязева 65б, пом.903, 9 этаж\n(посещение по предварительной договоренности)', verbose_name='Адрес / описание')),
                ('instagram_username', models.CharField(blank=True, default='sonder.homefeeling', max_length=120, verbose_name='Instagram (username)')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/sonder.homefeeling/', verbose_name='Instagram (URL)')),
                ('email', models.EmailField(blank=True, default='sonder.homefeeling@gmail.com', max_length=254, verbose_name='E-mail')),
                ('telegram_url', models.URLField(blank=True, default='https://t.me/sonderhomefeeling', verbose_name='Telegram (URL)')),
                ('map_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('map_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('map_zoom', models.PositiveSmallIntegerField(default=16, verbose_name='Зум карты')),
            ],
            options={
                'verbose_name': 'Страница «Контакты»',
                'verbose_name_plural': 'Страница «Контакты»',
            },
        ),
    ]
