# Generated by Django 5.2.7 on 2025-10-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_contactpagesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpagesettings',
            name='telegram_url',
        ),
    ]
