# Generated by Django 5.2.7 on 2025-10-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_contactpagesettings_telegram_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagesettings',
            options={'verbose_name': 'Страница «Главная»', 'verbose_name_plural': 'Страница «Главная»'},
        ),
    ]
