# Generated by Django 5.2.7 on 2025-10-08 15:34

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_homepagesettings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ДОСТАВКА И ОПЛАТА', max_length=120, verbose_name='Заголовок')),
                ('body_text', models.TextField(blank=True, default='', verbose_name='Текст страницы')),
                ('image_left', models.ImageField(blank=True, null=True, upload_to='delivery/', verbose_name='Фото слева')),
                ('image_left_crop', image_cropping.fields.ImageRatioField('image_left', '1000x1000', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка слева')),
                ('image_right', models.ImageField(blank=True, null=True, upload_to='delivery/', verbose_name='Фото справа')),
                ('image_right_crop', image_cropping.fields.ImageRatioField('image_right', '1000x1000', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка справа')),
                ('alt_left', models.CharField(blank=True, default='', max_length=200, verbose_name='Alt слева')),
                ('alt_right', models.CharField(blank=True, default='', max_length=200, verbose_name='Alt справа')),
            ],
            options={
                'verbose_name': 'Страница «Доставка и оплата»',
                'verbose_name_plural': 'Страница «Доставка и оплата»',
            },
        ),
    ]
