# Generated by Django 5.2.7 on 2025-10-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_deliverypagesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypagesettings',
            name='alt_left',
        ),
        migrations.RemoveField(
            model_name='deliverypagesettings',
            name='alt_right',
        ),
    ]
