# Generated by Django 5.2.7 on 2025-10-10 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_deliverypagesettings_alt_left_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='E-mail')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('tg_username', models.CharField(blank=True, max_length=64, verbose_name='Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='shop_custom_email_5770bc_idx'), models.Index(fields=['phone'], name='shop_custom_phone_70f608_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер заказа')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('paid', 'Оплачен'), ('fulfilling', 'Готовим'), ('shipped', 'Отправлен'), ('done', 'Завершён'), ('canceled', 'Отменён')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('delivery_provider', models.CharField(blank=True, max_length=50, verbose_name='Провайдер доставки')),
                ('delivery_method', models.CharField(blank=True, max_length=50, verbose_name='Метод доставки')),
                ('pickup_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес ПВЗ')),
                ('delivery_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес доставки')),
                ('currency', models.CharField(default='BYN', max_length=10, verbose_name='Валюта')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма товаров')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доставка')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итого')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий покупателя')),
                ('utm', models.JSONField(blank=True, null=True, verbose_name='UTM-данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен в')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название на момент покупки')),
                ('sku', models.CharField(blank=True, max_length=64, verbose_name='SKU')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Кол-во')),
                ('price_byn', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (BYN)')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма строки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('manual', 'Manual/Invoice'), ('stripe', 'Stripe'), ('yookassa', 'YooKassa'), ('liqpay', 'LiqPay')], default='manual', max_length=20, verbose_name='Провайдер')),
                ('provider_payment_id', models.CharField(blank=True, max_length=128, verbose_name='ID платежа у провайдера')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(default='BYN', max_length=10, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('succeeded', 'Успех'), ('failed', 'Неуспех'), ('refunded', 'Возврат')], default='pending', max_length=20, verbose_name='Статус платежа')),
                ('raw', models.JSONField(blank=True, null=True, verbose_name='Сырой ответ/событие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='shop.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='Служба')),
                ('tracking_number', models.CharField(blank=True, max_length=64, verbose_name='Трек-номер')),
                ('status', models.CharField(default='created', max_length=30, verbose_name='Статус отгрузки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shop.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Отгрузка',
                'verbose_name_plural': 'Отгрузки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='shop_order_status_700268_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='shop_order_created_86b012_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['email'], name='shop_order_email_fa7dab_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['number'], name='shop_order_number_39e72b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'status', 'created_at'], name='shop_paymen_provide_16bff1_idx'),
        ),
    ]
