# Generated by Django 5.2.7 on 2025-10-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_customer_order_orderitem_payment_shipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сумма товаров'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Итого'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='line_total',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Сумма строки'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_byn',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена (BYN)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_byn',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена, BYN'),
        ),
    ]
