# Generated by Django 5.2.7 on 2025-10-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_order_discount_alter_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Номер заказа'),
        ),
    ]
