# Generated by Django 5.2.7 on 2025-10-13 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(message='Только латинские буквы/цифры/._, 2–30 символов.', regex='^[A-Za-z0-9._]{2,30}$')], verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_contact',
            field=models.CharField(choices=[('email', 'E-mail'), ('phone', 'Телефон'), ('tg', 'Telegram'), ('ig', 'Instagram')], db_index=True, default='email', max_length=10, verbose_name='Предпочтительный способ связи'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('email', 'E-mail'), ('phone', 'Телефон'), ('tg', 'Telegram'), ('ig', 'Instagram')], db_index=True, help_text='Как попросили связаться именно по этому заказу', max_length=10, verbose_name='Способ связи (срез)'),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_value',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контакт (срез)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tg_username',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(message='Только латинские буквы/цифры/._, 2–30 символов.', regex='^[A-Za-z0-9._]{2,30}$')], verbose_name='Telegram'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['preferred_contact'], name='shop_custom_preferr_7d0fdd_idx'),
        ),
    ]
