# Generated by Django 5.2.7 on 2025-10-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_customer_instagram_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий по платежу'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('CARD', 'Карта'), ('CASH', 'Наличные')], default='CARD', max_length=20, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('succeeded', 'Успех'), ('failed', 'Ошибка'), ('refunded', 'Возврат')], default='pending', max_length=20, verbose_name='Статус платежа'),
        ),
    ]
