# Generated by Django 5.2.7 on 2025-10-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_payment_comment_alter_payment_provider_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.PositiveSmallIntegerField(db_index=True, default=100, help_text='Чем меньше число, тем выше категория в меню', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(max_length=30, verbose_name='Статус отгрузки'),
        ),
    ]
