# Generated by Django 5.2.7 on 2025-10-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_category_options_category_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='extra_title',
        ),
    ]
