# Generated by Django 5.2.7 on 2025-10-24 17:55

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_remove_product_extra_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productphoto',
            name='image_crop',
            field=image_cropping.fields.ImageRatioField('image', '1000x1000', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка'),
        ),
    ]
